#!/bin/bash

# WHILE

i=1

while [ $i -le 5 ]; do
    echo $i
    ((i++))
done

# FOR

for i in {1..5}; do
    echo "Número: $i"
done

# SWITCH

opcion=1

select opcion in "Opción 1" "Opción 2" "Opción 3"; do
    case $opcion in
        "Opción 1")
            echo "Has seleccionado Opción 1"
            ;;
        "Opción 2")
            echo "Has seleccionado Opción 2"
            ;;
        "Opción 3")
            echo "Has seleccionado Opción 3"
            ;;
        *)
            echo "Opción no reconocida"
            ;;
    esac
done


